const allProducts = [
    {
        name: "Men's Black Blazer",
        description: 'A comfortable and stylish Blazer.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787164/men-black-blazer_b3twgc.jpg',
        price: 3599,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.5,
        ratingCount: '2k',
        discount: 10,
        isFeatured: true,
        isBestSeller: true,
        isTrending: true,
        reviews: [], // dynamic population
    },
    {
        name: "Men's Shorts",
        description: 'Cool and stylish shorts.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787164/men-shorts_ybvo8f.jpg',
        price: 1099,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.1,
        ratingCount: '120',
        discount: 15,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Men's Blue Jeans",
        description: 'Stylish loose fit blue jeans.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787164/men-blue-jeans_moqcen.jpg',
        price: 1299,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.4,
        ratingCount: '510',
        discount: 5,
        isFeatured: false,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "White Sneakers for men",
        description: 'Trendy white sneakers for men.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787164/men-white-sneakers_l51bm2.jpg',
        price: 2149,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.3,
        ratingCount: '1k',
        discount: 20,
        isFeatured: false,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Men's Red T-Shirt",
        description: 'Cool red t-shirt perfect for summers.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-red-tshirt_qbaehq.jpg',
        price: 749,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.9,
        ratingCount: '1.2k',
        discount: 40,
        isFeatured: false,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Brown Leather Jacket for men",
        description: 'Stylish brown leather jacket essential for winters.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787164/men-brown-leather-jacket_erw8ex.jpg',
        price: 1799,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '1.1k',
        discount: 15,
        isFeatured: true,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Green Full-Sleeve Shirt for men",
        description: 'Full sleeve stylish green shirt.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787164/men-green-full-fleeve-shirt_mxhiok.jpg',
        price: 1049,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '650',
        discount: 20,
        isFeatured: true,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Men's Gray Cargo Pants",
        description: 'Comfortable and versatile cargo pants.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787164/men-gray-cargo-pants_wyhdel.jpg',
        price: 1699,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.2,
        ratingCount: '934',
        discount: 20,
        isFeatured: false,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Black Leather Belt for men",
        description: 'Rugged stylish leather belt.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-leather-belt_a1r4w4.jpg',
        price: 489,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '343',
        discount: 40,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Men's Blue Denim Jacket",
        description: 'Stylish and comfy denim jacket.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-denim-jacket_kt0o2d.jpg',
        price: 1159,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.7,
        ratingCount: '1k',
        discount: 40,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Metal Bracelet for Men",
        description: 'Essential metal accessory for men.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-metal-bracelet_ukaecq.jpg',
        price: 429,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.9,
        ratingCount: '502',
        discount: 10,
        isFeatured: false,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Olive Chalsea Boots for Men",
        description: 'Fashionable and durable olive boots.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-olive-chalsea-boots_f6etcf.jpg',
        price: 2399,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.2,
        ratingCount: '2.2k',
        discount: 40,
        isFeatured: false,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Men's Navy Blue Trousers",
        description: 'Perfect comfy navy trousers for formal and casual wear.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-navy-blue-trousers_ncehjg.jpg',
        price: 1199,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.1,
        ratingCount: '2k',
        discount: 10,
        isFeatured: false,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Powder Blue Shirt for Men",
        description: 'Stylish powder blue shirt essential for office and formal occasions',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-powder-blue-shirt_q3qjht.jpg',
        price: 1549,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.1,
        ratingCount: '1.6k',
        discount: 10,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Plain Shirt for Men",
        description: 'Fashionable and versatile plain shirt.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787165/men-plain-shirt_y6undq.jpg',
        price: 1099,
        category: 'men',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '1.4k',
        discount: 42,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Women's Black Leather Jacket",
        description: 'Stylish leather jacket for women.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787277/women-black-leather-jacket_v1vx0e.jpg',
        price: 2199,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.6,
        ratingCount: '3k',
        discount: 20,
        isFeatured: false,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Women's Black Sandals",
        description: 'Fashionable black sandals for women.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787277/women-black-sandals_qrfkhi.jpg',
        price: 1599,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.6,
        ratingCount: '1k',
        discount: 20,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Navy Blue Crop Top",
        description: 'Comfortable and stylish crop top.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787277/women-blue-crop-top_ql2mks.jpg',
        price: 799,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.1,
        ratingCount: '689',
        discount: 10,
        isFeatured: false,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Bracelet for Women",
        description: 'Cute and versatile metal accessory.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787278/women-bracelet_qneppj.jpg',
        price: 359,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.8,
        ratingCount: '1k',
        discount: 10,
        isFeatured: false,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Brown Sweater for Women",
        description: 'Comfy and stylish brown sweater essential for winters.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787278/women-brown-sweater_rfvmpg.jpg',
        price: 999,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.1,
        ratingCount: '1.3k',
        discount: 45,
        isFeatured: true,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "White Floral Dress for Women",
        description: 'Beautiful floral dress perfect for summers.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787278/women-floral-dress_qibynv.jpg',
        price: 1349,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.4,
        ratingCount: '1.8k',
        discount: 40,
        isFeatured: true,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "High Heels for Women",
        description: 'Elegant footwear for women.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787278/women-high-heels_rpfyt0.jpg',
        price: 2599,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.9,
        ratingCount: '1k',
        discount: 45,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Leather Belt for Women",
        description: 'Stylish and sturdy black leather belt.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787279/women-leather-belt_ywbq7g.jpg',
        price: 439,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.7,
        ratingCount: '245',
        discount: 10,
        isFeatured: false,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Light Pink Top for Women",
        description: 'Cute pink top for summers.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787279/women-pink-top_pfywtl.jpg',
        price: 659,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.8,
        ratingCount: '134',
        discount: 10,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Powder Blue Shirt for Women",
        description: 'Comfortable shirt for formal wear.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787279/women-powder-blue-shirt_gdkwp6.jpg',
        price: 1299,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '918',
        discount: 45,
        isFeatured: false,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Purple Full Sleeve T-Shirt for Women",
        description: 'Versatile and comfortable purple t-shirt.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787280/women-purple-full-sleeve-tshirt_ychxik.jpg',
        price: 689,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.6,
        ratingCount: '134',
        discount: 45,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Red Asymmetrical Party Dress for Women",
        description: 'Asymmetrical design dress perfect for formal and casual parties.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787280/women-red-assymetrical-dress_tdfbnp.jpg',
        price: 2799,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '3.2k',
        discount: 40,
        isFeatured: false,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Golden Analogue Watch for Women",
        description: 'Stylish analogue metal watch for women.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787280/women-watch_bhajil.jpg',
        price: 1499,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.9,
        ratingCount: '334',
        discount: 10,
        isFeatured: false,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "White Sneakers for Women",
        description: 'Comfortable and versatile all white sneakers.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787280/women-white-sneaker_uiigcj.jpg',
        price: 1669,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.4,
        ratingCount: '4.2k',
        discount: 10,
        isFeatured: true,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Yellow Frock for Women",
        description: 'Cute yellow frock perfect for summers.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787281/women-yellow-frock_sf1gwc.jpg',
        price: 1049,
        category: 'women',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.8,
        ratingCount: '112',
        discount: 20,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Kids' Patterned Blue Shirt",
        description: 'Cute and light patterned shirt for kids.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787600/kids-blue-shirt_jm1aru.jpg',
        price: 790,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '171',
        discount: 20,
        isFeatured: true,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Bracelet for Kids",
        description: 'light and cute bracelet.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787601/kids-bracelet_znkr3m.jpg',
        price: 231,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3,
        ratingCount: '94',
        discount: 20,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Pink Cap for Kids",
        description: 'Cute baby pink cap for kids.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787604/kids-cap_pbsuui.jpg',
        price: 379,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '171',
        discount: 40,
        isFeatured: false,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Black Jacket for Kids",
        description: 'Comfortable jacket for kids for winters',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787606/kids-jacket_gduw7s.jpg',
        price: 737,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4,
        ratingCount: '1k',
        discount: 40,
        isFeatured: true,
        isBestSeller: true,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Olive Green Pants for Kids",
        description: 'Loose fitting versatile olive pants.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787608/kids-pants_ilg8ry.jpg',
        price: 626,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.9,
        ratingCount: '236',
        discount: 45,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Printed T-Shirt for Kids",
        description: 'Comfortable and cute printed t-shirt.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787610/kids-printed-tshirt_ikxman.jpg',
        price: 467,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.1,
        ratingCount: '590',
        discount: 30,
        isFeatured: true,
        isBestSeller: true,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Casual Shoes for Kids",
        description: 'Very comfortable shoes for everyday wear.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787612/kids-shoes_xwbmto.jpg',
        price: 699,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.9,
        ratingCount: '302',
        discount: 10,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
    {
        name: "Light Blue Shorts for Kids",
        description: 'Cozy shorts designed for ultimate comfort.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787614/kids-shorts_fcipg1.jpg',
        price: 461,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 4.2,
        ratingCount: '875',
        discount: 40,
        isFeatured: false,
        isBestSeller: false,
        isTrending: true,
        reviews: [],
    },
    {
        name: "Yellow T-Shirt for Kids",
        description: 'Casual t-shirt for regular wear.',
        image: 'https://res.cloudinary.com/dly7d1x9l/image/upload/v1734787617/kids-tshirt_mxswp0.jpg',
        price: 399,
        category: 'kids',
        about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam labore vitae doloremque nisi quisquam ex itaque cum soluta eligendi delectus maxime quae illum eaque molestias, facere exercitationem!',
        rating: 3.8,
        ratingCount: '312',
        discount: 42,
        isFeatured: false,
        isBestSeller: false,
        isTrending: false,
        reviews: [],
    },
];

module.exports = allProducts;