export const products = [
    {
        id: 1,
        name: "Mens's Denim Jacket",
        price: '2,999',
        image: "/featuredProductsImages/men-denim-jacket.jpg",
        description: "Stylish piece of clothing for men",
        rating: '4.5',
        ratingCount: '3k'
      },
      {
        id: 2,
        name: "Floral Dress for women",
        price: '1,749',
        image: "/featuredProductsImages/floral-dress.jpg",
        description: "Summer essentials for women",
      },
      {
        id: 3,
        name: "Black Leather Belt",
        price: '899',
        image: "/featuredProductsImages/leather-belt.jpg",
        description: "Premium quality belts for men",
      },
      {
        id: 4,
        name: "Kids T-Shirt",
        price: '599',
        image: "/featuredProductsImages/kids-tshirt.jpg",
        description: "Plain T-Shirt for kids",
      },
      {
        id: 5,
        name: "Women's Sandals",
        price: '1,599',
        image: "/featuredProductsImages/women-sandal.jpg",
        description: "Stylish Sandal for women",
      },
      {
        id: 6,
        name: "Blue Men's Blazer",
        price: '1,679',
        image: "/featuredProductsImages/blue-men-blazer.jpg",
        description: "Essential piece of clothing for men",
      },
      {
        id: 1,
        name: "Mens's Denim Jacket",
        price: '2,999',
        image: "/featuredProductsImages/men-denim-jacket.jpg",
        description: "Stylish piece of clothing for men",
      },
      {
        id: 2,
        name: "Floral Dress for women",
        price: '1,749',
        image: "/featuredProductsImages/floral-dress.jpg",
        description: "Summer essentials for women",
      },
      {
        id: 3,
        name: "Black Leather Belt",
        price: '899',
        image: "/featuredProductsImages/leather-belt.jpg",
        description: "Premium quality belts for men",
      },
      {
        id: 4,
        name: "Kids T-Shirt",
        price: '599',
        image: "/featuredProductsImages/kids-tshirt.jpg",
        description: "Plain T-Shirt for kids",
      },
      {
        id: 5,
        name: "Women's Sandals",
        price: '1,599',
        image: "/featuredProductsImages/women-sandal.jpg",
        description: "Stylish Sandal for women",
      },
      {
        id: 6,
        name: "Blue Men's Blazer",
        price: '1,679',
        image: "/featuredProductsImages/blue-men-blazer.jpg",
        description: "Essential piece of clothing for men",
      },
      {
        id: 1,
        name: "Mens's Denim Jacket",
        price: '2,999',
        image: "/featuredProductsImages/men-denim-jacket.jpg",
        description: "Stylish piece of clothing for men",
      },
      {
        id: 2,
        name: "Floral Dress for women",
        price: '1,749',
        image: "/featuredProductsImages/floral-dress.jpg",
        description: "Summer essentials for women",
      },
      {
        id: 3,
        name: "Black Leather Belt",
        price: '899',
        image: "/featuredProductsImages/leather-belt.jpg",
        description: "Premium quality belts for men",
      },
      {
        id: 4,
        name: "Kids T-Shirt",
        price: '599',
        image: "/featuredProductsImages/kids-tshirt.jpg",
        description: "Plain T-Shirt for kids",
      },
      {
        id: 5,
        name: "Women's Sandals",
        price: '1,599',
        image: "/featuredProductsImages/women-sandal.jpg",
        description: "Stylish Sandal for women",
      },
      {
        id: 6,
        name: "Blue Men's Blazer",
        price: '1,679',
        image: "/featuredProductsImages/blue-men-blazer.jpg",
        description: "Essential piece of clothing for men",
      },
      {
        id: 1,
        name: "Mens's Denim Jacket",
        price: '2,999',
        image: "/featuredProductsImages/men-denim-jacket.jpg",
        description: "Stylish piece of clothing for men",
      },
      {
        id: 2,
        name: "Floral Dress for women",
        price: '1,749',
        image: "/featuredProductsImages/floral-dress.jpg",
        description: "Summer essentials for women",
      },
      {
        id: 3,
        name: "Black Leather Belt",
        price: '899',
        image: "/featuredProductsImages/leather-belt.jpg",
        description: "Premium quality belts for men",
      },
      {
        id: 4,
        name: "Kids T-Shirt",
        price: '599',
        image: "/featuredProductsImages/kids-tshirt.jpg",
        description: "Plain T-Shirt for kids",
      },
      {
        id: 5,
        name: "Women's Sandals",
        price: '1,599',
        image: "/featuredProductsImages/women-sandal.jpg",
        description: "Stylish Sandal for women",
      },
      {
        id: 6,
        name: "Blue Men's Blazer",
        price: '1,679',
        image: "/featuredProductsImages/blue-men-blazer.jpg",
        description: "Essential piece of clothing for men",
      },
] 
